secrets:
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  postgres_db:
    file: ./secrets/postgres_db.txt

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres_db
    restart: always
    # Add command to use custom config
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - forecast_net
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db

volumes:
  postgres_data:

networks:
  forecast_net:
    driver: bridge
